# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  # url = "/about"
  weight = 10

[[main]]
  name = "About RCODI"
  url = "/about"
  weight = 11
  parent = "About"

[[main]]
  name = "Our People"
  url = "/our-people"
  weight = 12
  parent = "About"
  
[[main]]
  name = "Our Alumni"
  url = "/our-alumni"
  weight = 13
  parent = "About"
  
[[main]]
  name = "Affiliated Faculty"
  url = "/affiliated-faculty"
  weight = 14
  parent = "About"
  
[[main]]
  name = "Partners and Sponsors"
  url = "/partners-sponsors"
  weight = 15
  parent = "About"

[[main]]
  name = "Blog"
  url = "/post"
  weight = 20
  # parent = "About"

[[main]]
  name = "Projects"
  url = "/our-projects"
  weight = 30

# [[main]]
#   name = "Talks"
#   url = "#talks"
#   weight = 40

[[main]]
  name = "Publications"
  url = "/references"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
  name = "Get Involved"
  url = "/get-involved"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
